namespace Hma.Infrastructure.SqlServer;

// Generated from 11_08_2026.xlsx (ops board). Do not parse Excel at runtime.
public static class LegacyData
{
    public static readonly (string Code, string[] Aliases)[] Customers =
    [
        ("123", []),
        ("ACT", []),
        ("AIT", []),
        ("ANC", []),
        ("ART", []),
        ("ASC", []),
        ("ASCVN", []),
        ("ASG", []),
        ("ASTI", []),
        ("ATA", []),
        ("ATM", []),
        ("ATO", []),
        ("ATT", []),
        ("AZ", []),
        ("BEE", []),
        ("biển vàng", ["biẻn vàng"]),
        ("BONDEX", []),
        ("BTP", []),
        ("CHL", []),
        ("châu hantorans", []),
        ("CJ", []),
        ("CNC", []),
        ("CRANE", []),
        ("DAIJIN", []),
        ("DONGJIN", ["đongjin"]),
        ("DTH", []),
        ("dược nam hà", []),
        ("ECAGO", []),
        ("ECARGO", []),
        ("EUSU", []),
        ("FEILIKS", []),
        ("FFHAN", []),
        ("GEODIS", []),
        ("GLOBALCOM", []),
        ("GLOVIS", []),
        ("GNHAN", []),
        ("ha long", ["hạ long"]),
        ("HELLMAN", []),
        ("HENGTAI", []),
        ("HFRIEND", []),
        ("hiên hung Qn", ["hiển hưng Qn"]),
        ("HKIM", []),
        ("huy sck", []),
        ("huệ VB", []),
        ("hạnh sck", []),
        ("hải đăng", ["hai dang"]),
        ("INTERMAX", []),
        ("IVTRANS", []),
        ("JH", []),
        ("JL", []),
        ("JS", []),
        ("KAS", []),
        ("KCTC", []),
        ("kiều linh sck", []),
        ("KMG", []),
        ("KORCHINA", []),
        ("KORNET", []),
        ("KORVINA", []),
        ("LGI", []),
        ("linh hanotrans", []),
        ("LITRI", []),
        ("liên kết", []),
        ("LOXSON", []),
        ("LXT", []),
        ("mai vtri", ["maiv tri"]),
        ("MARUZEN", []),
        ("MASTER", []),
        ("MAX", []),
        ("MAXFEED", []),
        ("MJ", []),
        ("MTL", []),
        ("MTL hanwa", []),
        ("NAGEL", []),
        ("nam phương", []),
        ("NAMYANG", []),
        ("NEWDAYS", []),
        ("ngoài long maxfeed", []),
        ("Nguyệt IRIFUNE 0902108098", []),
        ("nhi kmg", []),
        ("NTS", []),
        ("PACIFIC", []),
        ("PALM", []),
        ("PANDA", []),
        ("PANDABN", []),
        ("PARTNER", []),
        ("PHOENIX", []),
        ("phương đong", ["phương đông"]),
        ("PL", []),
        ("PNS", []),
        ("PTV", []),
        ("quang sck", []),
        ("ROYAL", []),
        ("SAFI", []),
        ("SAFO", []),
        ("SCAN", []),
        ("SCS", []),
        ("SCT", []),
        ("SHEGYANG", []),
        ("SHENGYANG", ["sheng yang"]),
        ("SME", []),
        ("sme hầnm", []),
        ("SOTRAN", []),
        ("SSG", []),
        ("STT8", []),
        ("TCC", []),
        ("TEC", []),
        ("THYGESEN", []),
        ("thông đồ", []),
        ("thủ đô", []),
        ("tiến hùng", []),
        ("TNN", []),
        ("trường thành", []),
        ("trọng tín", []),
        ("tuấn sck", []),
        ("UI", []),
        ("UNILO", []),
        ("USCOM", []),
        ("V one", []),
        ("VAST", []),
        ("VDC", []),
        ("VICONSHIP", ["viconship\\"]),
        ("VIETBILLS", []),
        ("VIETTRANS", []),
        ("VIETUNI", []),
        ("VMVV", []),
        ("VNL", []),
        ("vs team", []),
        ("VTHĐ", []),
        ("VVMV", []),
        ("vũ hiếu", []),
        ("vương hải", []),
        ("WINGTRANS", []),
        ("YAMATO", []),
        ("đong tài", ["đông tài"]),
        ("đông oia", []),
        ("đại tây dương", []),
        ("đại đông", []),
        ("đức thịnh", []),
    ];

    public static readonly string[] Drivers =
    [
        "An Minh Hệ",
        "Bùi Ngọc Tuân",
        "Bùi Ngọc Tuấn",
        "Bùi Trần Phúc",
        "Bùi Văn Hà",
        "Bùi Văn Long",
        "Bùi Văn Thạo",
        "Bùi Việt Đức",
        "Buì Xuân Thành",
        "Cao Văn Tuấn",
        "Đàm Văn Anh",
        "Đặng Đức Đinh",
        "Đặng Thành Dương",
        "Đặng Văn Nho",
        "Đào Văn Điển",
        "Đinh Xuân Ân",
        "Đỗ Chí Linh",
        "Đỗ Minh Quân",
        "Đỗ Minh Xuân",
        "Đỗ Quang Vinh",
        "Đỗ Tất Thành",
        "Đỗ Tiến Chung",
        "Đỗ Tiến Dũng",
        "Đỗ Trọng Thanh",
        "Đỗ Văn Cường",
        "Đỗ Văn Phượng",
        "Đỗ Văn Thạo",
        "Đỗ Xuân Trường",
        "Đoàn Văn Mạnh",
        "Đồng Văn Phương",
        "Dương Minh Châu",
        "Hà Quang Lương",
        "Hà Văn Bảo",
        "Hoàng Đình Tuân",
        "Hoàng Thanh Tùng",
        "Hoàng Văn Công",
        "Hoàng Văn Linh",
        "Hoàng Văn Tiềm",
        "Kiều Văn Cường",
        "Lê Danh Khoa",
        "Lê Đức Anh",
        "Lê Đức Lâm",
        "Lê Hoàng Thanh",
        "Lê Minh Thái",
        "Lê Quang Tuấn",
        "Lê Quốc Huy",
        "Lê Sỹ Chung",
        "Lê Thiếu Vũ",
        "Lê Văn Lâm",
        "Lê Văn Lý",
        "Lê Văn Mạnh",
        "Lê Văn Mừng",
        "Lê Văn Quý",
        "Lê Văn Thái",
        "Lê Văn Tiến",
        "Lê Văn Tuấn",
        "Lê Văn Việt",
        "Lê Văn Vui",
        "Lương Việt Nam",
        "Lưu Văn Hải",
        "Mai Văn Thành",
        "Nghiêm Văn Hai",
        "Nghiêm Văn Tầm",
        "Ngô Anh Tuấn",
        "Ngô Công Tú",
        "Ngô Quang Dũng",
        "Ngô Thanh Phương",
        "Ngô Thanh Yên",
        "Ngô Văn Dung",
        "Ngô Văn Hạnh",
        "Ngô Văn Linh",
        "Ngô Văn Vương",
        "Nguyễn Công Sơn",
        "Nguyễn Đan Chiến",
        "Nguyễn Đình Bảo",
        "Nguyễn Đình Chương",
        "Nguyễn Đức Lợi",
        "Nguyễn Đức Việt",
        "Nguyễn Duy Chinh",
        "Nguyễn Duy Phóng",
        "Nguyễn Hải Việt",
        "Nguyễn Hoài Giao",
        "Nguyễn Hoàng Nam",
        "Nguyễn Hồng Phong",
        "Nguyễn Hữu Khải",
        "Nguyễn Hữu Oanh",
        "Nguyễn Mạnh Cường",
        "Nguyễn Minh Đức",
        "Nguyễn Minh Dũng",
        "Nguyễn Minh Hắc",
        "Nguyễn Minh Hiếu",
        "Nguyễn Minh Hoà",
        "Nguyễn Minh Hoàng",
        "Nguyễn Minh Huấn",
        "Nguyễn Minh Mạnh",
        "Nguyễn Minh Trường",
        "Nguyễn Ngọc Chinh",
        "Nguyễn Ngọc Dũng",
        "Nguyễn Ngọc Duy",
        "Nguyễn Ngọc Hậu",
        "Nguyễn Như Cương",
        "Nguyễn Như Tô",
        "Nguyễn Quang Huệ",
        "Nguyễn Quốc Huy",
        "Nguyễn Quốc Triệu",
        "Nguyễn Quý Long",
        "Nguyễn Sinh Cầu",
        "Nguyễn Thanh Bình",
        "Nguyễn Thành Công",
        "Nguyễn Thanh Hải",
        "Nguyễn Thành Long",
        "Nguyễn Thành Nguyên",
        "Nguyễn Thế Anh",
        "Nguyễn Thế Hoà",
        "Nguyễn Thế Hoan",
        "Nguyễn Thế Hùng",
        "Nguyễn Thế Quang",
        "Nguyễn Tiến Lộc",
        "Nguyễn Trọng Ánh",
        "Nguyễn Trọng Hiếu",
        "Nguyễn Trung Quý Thịnh",
        "Nguyễn Tuấn Anh",
        "nguyễn Tuấn Bạo",
        "Nguyễn Văn Biên",
        "Nguyễn Văn Bình",
        "Nguyễn Văn Cảnh",
        "Nguyễn Văn Công",
        "Nguyễn Văn Cường",
        "Nguyễn Văn Đăng",
        "Nguyễn Văn Đông",
        "Nguyễn Văn Giang",
        "Nguyễn Văn Hà",
        "Nguyễn Văn Hải",
        "Nguyễn Văn Hậu",
        "Nguyễn Văn Hiệp",
        "Nguyễn Văn Hoạch",
        "Nguyễn Văn Hoàng",
        "Nguyễn Văn Hồi",
        "Nguyễn Văn Hợp",
        "Nguyễn Văn Khánh",
        "Nguyễn Văn Long",
        "Nguyễn Văn Lý",
        "Nguyễn Văn Minh",
        "Nguyễn Văn Nam",
        "Nguyễn Văn Ngát",
        "Nguyễn Văn Nguyên",
        "Nguyễn Văn Nhật",
        "Nguyễn Văn Nhường",
        "Nguyễn Văn Quang",
        "Nguyễn Văn Quỳnh",
        "Nguyễn Văn Sinh",
        "Nguyễn Văn Sơn",
        "Nguyễn Văn Tâm",
        "Nguyễn Văn Tập",
        "Nguyễn Văn Thắng",
        "Nguyễn Văn Thanh",
        "Nguyễn Văn Thịnh",
        "Nguyễn Văn Thuỳ",
        "Nguyễn Văn Tiến",
        "Nguyễn Văn Tiệp",
        "Nguyễn Văn Trọng",
        "Nguyễn Văn Tuấn",
        "Nguyễn Văn Tường",
        "Nguyễn Xuân Chiến",
        "Phạm Minh Đức",
        "Phạm Tiến Sơn",
        "Phạm Trọng Kiên",
        "Phạm Văn Đông",
        "Phạm Văn Phượng",
        "Phạm Xuân Huỳnh",
        "Phan Quốc Doanh",
        "Phan Văn Bình",
        "Phan Văn Linh",
        "Phan Văn Ninh",
        "Phù Đức Quân",
        "Phùng Đình Duy",
        "Phùng Đình Thùy",
        "Quách Thanh Như",
        "Tạ Văn Khánh",
        "Tạ Văn Phước",
        "Tạ Văn Việt",
        "Tẩn Láo San",
        "Tô Phúc Thịnh",
        "Tô Tiến Định",
        "Tòng Văn Thiệu",
        "Trần Anh Tú",
        "Trần Đình Công",
        "Trần Đình Quang",
        "Trần Đình Thắng",
        "Trần Đình Trọng",
        "Trần Đức Chung",
        "Trần Đức Tâm",
        "Trần Đức Xuân",
        "Trần Hoàng Duy",
        "Trần Khánh Ngọc",
        "Trần Ngọc Lợi",
        "Trần Ngọc Tuyên",
        "Trần Quang Phương",
        "Trần Văn Ánh",
        "Trần Văn Cường",
        "Trần Văn Dũng",
        "Trần Văn Hà",
        "Trần Văn Hải",
        "Trần Văn Hiệp",
        "Trần Văn Hoàng",
        "Trân Văn Hội",
        "Trần Văn Luận",
        "Trần Văn Nam",
        "Trần văn Nhất",
        "Trần Văn Nhật",
        "Trần Văn Toàn",
        "Trần Văn Tới",
        "Trần Văn Trưởng",
        "Trần Văn Tuấn",
        "Trần Văn Tươi",
        "Trịnh Thế Hoàng",
        "Trịnh Văn Sức",
        "Trương Anh Hào",
        "Võ Huy Liệu",
        "Vũ Hồng Lâm",
        "Vũ Hồng Sơn",
        "Vũ Văn Đức",
        "Vũ Văn Tuyên",
        "Vương Văn Nam",
        "Vương Văn Thuận",
    ];

    public static readonly (string Plate, string? TypeCode)[] Vehicles =
    [
        ("17C-12351", "1.25T"),
        ("29C-23759", "10T"),
        ("29C-25804", "10T"),
        ("29C-27252", null),
        ("29C-41831", "8T"),
        ("29C-42258", "8T"),
        ("29C-62832", "8T"),
        ("29C-63440", null),
        ("29C-90783", null),
        ("29C-91076", "1.25T"),
        ("29C-91489", "10T"),
        ("29C-91897", "1.25T"),
        ("29C-93761", null),
        ("29C-96852", "10T"),
        ("29C-98493", "1.5T"),
        ("29C-98662", "2.5T"),
        ("29C-99267", "1.5T"),
        ("29C-99432", "2.5T"),
        ("29C-99817", "1.5T"),
        ("29C-99866", "2.5T"),
        ("29E-03447", "1.5T"),
        ("29E-14703", "1.5T"),
        ("29E-14718", "2.5T"),
        ("29E-14731", "10T"),
        ("29E-14741", "1.5T"),
        ("29E-14746", "10T"),
        ("29E-15352", "10T"),
        ("29E-15360", "10T"),
        ("29E-15363", "10T"),
        ("29E-19046", "10T"),
        ("29E-19108", "2.5T"),
        ("29E-20507", null),
        ("29E-21604", "2.5T"),
        ("29E-25754", "10T"),
        ("29E-25763", "10T"),
        ("29E-25766", "8T"),
        ("29E-25784", "8T"),
        ("29E-25793", "2.5T"),
        ("29E-25797", "10T"),
        ("29E-25808", "10T"),
        ("29E-25823", null),
        ("29E-25904", "10T"),
        ("29E-25960", "8T"),
        ("29E-25997", "10T"),
        ("29E-26201", "2.5T"),
        ("29E-26218", "1.5T"),
        ("29E-26221", "10T"),
        ("29E-26240", "10T"),
        ("29E-26241", "1.5T"),
        ("29E-26264", "10T"),
        ("29E-26438", "2.5T"),
        ("29E-26694", "10T"),
        ("29E-26706", "1.25T"),
        ("29E-26731", "10T"),
        ("29E-26738", null),
        ("29E-38020", "10T"),
        ("29E-38094", "8T"),
        ("29E-38455", "1.5T"),
        ("29E-38459", "1.25T"),
        ("29E-39956", "1.25T"),
        ("29E-57032", "10T"),
        ("29E-60409", "10T"),
        ("29E-60415", "2.5T"),
        ("29E-60421", "10T"),
        ("29E-60423", null),
        ("29E-60424", null),
        ("29E-60428", "10T"),
        ("29E-60450", "10T"),
        ("29E-60451", "2.5T"),
        ("29E-60458", "10T"),
        ("29E-60464", "2.5T"),
        ("29E-60474", "10T"),
        ("29E-60497", "10T"),
        ("29E-61612", "1.5T"),
        ("29E-61683", "1.5T"),
        ("29E-61717", "8T"),
        ("29E-61763", "10T"),
        ("29E-66229", "1.5T"),
        ("29E-68413", null),
        ("29E-68432", "10T"),
        ("29E-72445", "1.5T"),
        ("29E-72475", null),
        ("29E-73027", "8T"),
        ("29E-73174", "1.5T"),
        ("29E-73178", null),
        ("29E-73191", "2.5T"),
        ("29E-75341", "1.25T"),
        ("29E-75342", "2.5T"),
        ("29E-75361", "1.5T"),
        ("29E-75467", "1.5T"),
        ("29E-80205", "2.5T"),
        ("29E-80208", "10T"),
        ("29E-80210", "1.25T"),
        ("29E-80221", "10T"),
        ("29E-81504", "8T"),
        ("29E-81519", "10T"),
        ("29E-81541", "10T"),
        ("29E-81561", "1.5T"),
        ("29E-81584", "2.5T"),
        ("29E-81585", "10T"),
        ("29E-81659", "1.25T"),
        ("29E-82297", "8T"),
        ("29E-82382", null),
        ("29E-82384", "1.25T"),
        ("29E-85365", "8T"),
        ("29F-05632", "10T"),
        ("29F-05924", null),
        ("29H-03497", "8T"),
        ("29H-16088", "1.5T"),
        ("29H-16749", "8T"),
        ("29H-20016", "8T"),
        ("29H-20092", "2.5T"),
        ("29H-20360", "2.5T"),
        ("29H-20491", "8T"),
        ("29H-20904", "1.5T"),
        ("29H-24342", "10T"),
        ("29H-24560", "2.5T"),
        ("29H-24593", "8T"),
        ("29H-24640", "1.5T"),
        ("29H-24678", "8T"),
        ("29H-27187", "2.5T"),
        ("29H-27552", "1.25T"),
        ("29H-32082", "10T"),
        ("29H-37462", "2.5T"),
        ("29H-37692", "1.25T"),
        ("29H-37744", null),
        ("29H-40053", "2.5T"),
        ("29H-40352", "1.25T"),
        ("29H-40589", "1.25T"),
        ("29H-40766", "2.5T"),
        ("29H-57927", "1.25T"),
        ("29H-65121", "1.25T"),
        ("29H-70616", "10T"),
        ("29H-70651", "10T"),
        ("29H-70701", "10T"),
        ("29H-70705", "1.25T"),
        ("29H-70710", "1.5T"),
        ("29H-70711", "1.5T"),
        ("29H-70720", "2.5T"),
        ("29H-70770", "8T"),
        ("29H-70853", "10T"),
        ("29H-71509", "2.5T"),
        ("29H-71523", "1.25T"),
        ("29H-71646", "2.5T"),
        ("29H-71659", "10T"),
        ("29H-71772", "8T"),
        ("29H-72832", "1.25T"),
        ("29H-72954", "1.25T"),
        ("29H-72981", "2.5T"),
        ("29H-73029", "10T"),
        ("29H-75646", "10T"),
        ("29H-75693", "10T"),
        ("29H-75707", "1.25T"),
        ("29H-75721", "10T"),
        ("29H-75771", "8T"),
        ("29H-75837", "8T"),
        ("29H-75927", "8T"),
        ("29H-76525", "8T"),
        ("29H-76538", "2.5T"),
        ("29H-76574", "8T"),
        ("29H-76732", "2.5T"),
        ("29H-76852", null),
        ("29H-76892", "2.5T"),
        ("29H-76897", "2.5T"),
        ("29H-76911", "10T"),
        ("29H-76913", "10T"),
        ("29H-76957", "1.25T"),
        ("29H-76996", null),
        ("29H-79129", null),
        ("29H-79191", "2.5T"),
        ("29H-79327", "1.25T"),
        ("29H-80176", "10T"),
        ("29H-81186", "2.5T"),
        ("29H-81285", "2.5T"),
        ("29H-81299", "1.5T"),
        ("29H-81356", "2.5T"),
        ("29H-81408", "1.25T"),
        ("29H-81454", "1.5T"),
        ("29H-81455", "2.5T"),
        ("29H-82411", "1.25T"),
        ("29H-82447", "1.25T"),
        ("29H-83178", "10T"),
        ("29H-83585", "1.25T"),
        ("29H-84132", null),
        ("29H-84141", "1.25T"),
        ("29H-84182", "1.25T"),
        ("29H-84183", "2.5T"),
        ("29H-84256", null),
        ("29H-84265", "8T"),
        ("29H-84272", "2.5T"),
        ("29H-86368", "1.25T"),
        ("29H-86374", "10T"),
        ("29H-88332", "1.25T"),
        ("29H-88352", "1.25T"),
        ("29H-88359", "1.25T"),
        ("29H-92016", "1.5T"),
        ("29H-92048", "1.25T"),
        ("29H-92079", "1.25T"),
        ("29H-95052", "2.5T"),
        ("29H-95103", "1.25T"),
        ("29H-95131", "1.25T"),
        ("29H-95261", "1.5T"),
        ("29H-99339", "10T"),
        ("29H-99390", "10T"),
        ("29H-99453", "10T"),
        ("29H-99464", "8T"),
        ("29H-99519", "10T"),
        ("29H-99526", null),
        ("29H-99568", "1.5T"),
        ("29H-99630", "10T"),
        ("29H-99640", "10T"),
        ("29H-99662", "1.5T"),
        ("29H-99696", "10T"),
        ("29H-99749", "2.5T"),
        ("29H-99790", "2.5T"),
        ("29K-05407", "1.25T"),
        ("29K-05422", "1.5T"),
        ("29K-05442", "2.5T"),
        ("29K-05457", "10T"),
        ("29K-05484", "2.5T"),
        ("29K-05515", "1.25T"),
        ("29K-05519", null),
        ("29K-05565", "2.5T"),
        ("29K-05580", null),
        ("29K-05620", "2.5T"),
        ("29K-05624", "1.5T"),
        ("29K-05702", "1.5T"),
        ("29K-05722", "10T"),
        ("29K-05805", "1.25T"),
        ("29K-05833", "8T"),
        ("29K-05932", "1.5T"),
        ("29K-05944", "10T"),
        ("29K-05984", "1.5T"),
        ("34C-27943", "2.5T"),
        ("88H-02532", "2.5T"),
        ("99C-20574", "1.5T"),
    ];

    public static readonly (string Code, string Name, string[] Aliases)[] Locations =
    [
        ("DHA", "Công ty TNHH một thành viên DHA Bắc Ninh", []),
        ("NMQ", "Công ty cổ phần tiếp vận NMQ", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("alsw", "alsw", []),
        ("an tảo TP hưng yên", "an tảo TP hưng yên", []),
        ("ân thi", "ân thi", []),
        ("asg", "asg", []),
        ("bắc ninh", "bắc ninh", []),
        ("bá thiện", "bá thiện", []),
        ("bình xuyên", "bình xuyên", []),
        ("BT", "BT", ["BT kiểm", "BT lạnh"]),
        ("BX", "BX", ["bx cao tốc"]),
        ("BX 2", "BX 2", []),
        ("cẩm giàng", "cẩm giàng", []),
        ("cẩm giàng HD", "cẩm giàng HD", []),
        ("cẩm khê", "cẩm khê", []),
        ("cảng Hp", "cảng Hp", ["cảng Hp lạnh"]),
        ("cầu giấy", "cầu giấy", []),
        ("châu sơn", "châu sơn", []),
        ("chuyển kho als", "chuyển kho als", []),
        ("Đại An", "Đại An", []),
        ("đại đồng", "đại đồng", ["Đại đòng"]),
        ("đà nẵng", "đà nẵng", []),
        ("định hoá thái nguyên", "định hoá thái nguyên", []),
        ("đình trám", "đình trám", ["kiểm đình trám"]),
        ("đong hưng thái bình", "đong hưng thái bình", []),
        ("đông mai", "đông mai", []),
        ("đong mai QN", "đong mai QN", ["đong mai Qn, 100k chờ lấy hàng"]),
        ("đông trièu QN", "đông trièu QN", []),
        ("đồng văn", "đồng văn", ["đòng văn"]),
        ("dthuy", "dthuy", ["D thuy"]),
        ("dthy", "dthy", []),
        ("đường hào HY", "đường hào HY", []),
        ("đv", "đv", ["đv lạnh"]),
        ("dv 4", "dv 4", ["ĐV 4"]),
        ("gia bình", "gia bình", []),
        ("hà đong", "hà đong", []),
        ("hà đong giấy", "hà đong giấy", ["hà đông giáy", "hà đông giấy"]),
        ("hà đong giấy + Hn giấy", "hà đong giấy + Hn giấy", []),
        ("hải dương", "hải dương", []),
        ("hải hà", "hải hà", []),
        ("hạ long", "hạ long", []),
        ("hà nội giấy", "hà nội giấy", ["hà nội giấy 2 điểm"]),
        ("hạp lĩnh", "hạp lĩnh", ["hạp lĩnh ;lạnh"]),
        ("hà trung", "hà trung", []),
        ("hiệp hoà", "hiệp hoà", []),
        ("Hn", "Hn", []),
        ("Hn giấy", "Hn giấy", []),
        ("hoài đức", "hoài đức", []),
        ("hoà phú", "hoà phú", ["hòa phú"]),
        ("hoa quân nghệ an", "hoa quân nghệ an", []),
        ("hoà xá", "hoà xá", []),
        ("honda phúc yên", "honda phúc yên", []),
        ("hồng bàng HP", "hồng bàng HP", []),
        ("hợp thịnh BG", "hợp thịnh BG", []),
        ("hQQV", "hQQV", []),
        ("HQ tiên sơn", "HQ tiên sơn", []),
        ("HQVP", "HQVP", []),
        ("hưng hà", "hưng hà", []),
        ("HY", "HY", []),
        ("KCn nội bài", "KCn nội bài", []),
        ("khai quang", "khai quang", ["khai quang bốc"]),
        ("kim thành HD", "kim thành HD", []),
        ("KNQ BT", "KNQ BT", ["KNQ BT chờ 200k"]),
        ("KNQ hà nam", "KNQ hà nam", []),
        ("KQ", "KQ", []),
        ("lâm thao", "lâm thao", []),
        ("lạng giang", "lạng giang", []),
        ("lập thạch", "lập thạch", []),
        ("LGD", "LGD", ["LGD lạnh vé", "LGD rung vé", "LGD vé"]),
        ("LGE", "LGE", [":LGE"]),
        ("Lgi", "Lgi", ["Lgi vé"]),
        ("lục nam", "lục nam", []),
        ("lương sơn", "lương sơn", []),
        ("mong dương Qn", "mong dương Qn", []),
        ("mỹ hào", "mỹ hào", []),
        ("mỹ hào hy", "mỹ hào hy", []),
        ("Mỹ thuận nam định", "Mỹ thuận nam định", []),
        ("nam định 2 chiều", "nam định 2 chiều", []),
        ("nam sách", "nam sách", []),
        ("nb", "nb", ["2 kho nb", "4 kho NB", "N b", "NB 2 kho", "NB lạnh", "nb , vé", "nb 3 kho + chờ 200k", "nb cao tốc", "nb chờ 150k", "nb chờ 3 giơf", "nb chờ 300k", "nb kiẻm", "nb kiểm", "nb ko hàng", "nb lưu xe", "nb lưu đêm", "nb lưu đêm + 2 kho", "nb lưu đêm 2 kho", "nb vé", "nb vé ct", "nb đeem", "nb, 200k chờ", "nb, vé", "nb\\"]),
        ("nbg", "nbg", []),
        ("nb nguyên", "nb nguyên", []),
        ("nb QĐ", "nb QĐ", ["nb QĐ lưu ca đêm NBA", "nb QĐ lưu đêm"]),
        ("nghĩa trụ HY", "nghĩa trụ HY", []),
        ("nghi lộc", "nghi lộc", []),
        ("NGọc hồi", "NGọc hồi", ["ngọc hôi"]),
        ("NGuyên khê", "NGuyên khê", []),
        ("nhà máy chè", "nhà máy chè", []),
        ("Nn", "Nn", []),
        ("nomura", "nomura", []),
        ("phổ yên", "phổ yên", []),
        ("phú bài huế", "phú bài huế", []),
        ("Phúc điền", "Phúc điền", []),
        ("phúc thọ", "phúc thọ", []),
        ("phúc yên", "phúc yên", []),
        ("phú hà", "phú hà", []),
        ("phủ lý", "phủ lý", ["phủ lý lưu nhà máy"]),
        ("phú nghĩa", "phú nghĩa", []),
        ("phù ninh", "phù ninh", []),
        ("Phú thọ", "Phú thọ", []),
        ("P NỐi A", "P NỐi A", []),
        ("P NỐi B", "P NỐi B", []),
        ("Qchau", "Qchau", ["Qchau lạnh", "Qchau, chèn 80k"]),
        ("QM", "QM", ["QM lạnh"]),
        ("quang minh", "quang minh", []),
        ("quế võ", "quế võ", []),
        ("QV", "QV", ["QV kiểm", "QV lạnh"]),
        ("QV 2", "QV 2", []),
        ("QV 3", "QV 3", []),
        ("sevt", "sevt", ["sevt bốc 100k"]),
        ("shinwon", "shinwon", []),
        ("sóc sơn", "sóc sơn", []),
        ("sơn đồng Hn", "sơn đồng Hn", []),
        ("sông cong", "sông cong", ["song cong", "sông công"]),
        ("song khê", "song khê", []),
        ("sông khoai QN", "sông khoai QN", []),
        ("sơn la", "sơn la", ["sơn la, 560k lưu đêm"]),
        ("tam dương", "tam dương", []),
        ("tân chi", "tân chi", []),
        ("tân quang", "tân quang", []),
        ("tân trường", "tân trường", []),
        ("tân yên", "tân yên", []),
        ("thạch thất", "thạch thất", []),
        ("thái bình", "thái bình", []),
        ("thăng long", "thăng long", []),
        ("thăng long 2", "thăng long 2", ["thăng long 2 lạnh"]),
        ("thanh hoá", "thanh hoá", []),
        ("thanh thuỷ", "thanh thuỷ", []),
        ("thanh trì", "thanh trì", []),
        ("thuận thành", "thuận thành", []),
        ("thường tín", "thường tín", []),
        ("thuỵ vân", "thuỵ vân", []),
        ("tiên du", "tiên du", []),
        ("tiên sơn", "tiên sơn", ["tiên sợn"]),
        ("tiên xuân thạch thất", "tiên xuân thạch thất", []),
        ("T long", "T long", ["T long lạnh"]),
        ("T long 2", "T long 2", []),
        ("T longb", "T longb", []),
        ("Tp bắc giang", "Tp bắc giang", []),
        ("TP bắc ninh", "TP bắc ninh", []),
        ("TP hải dương", "TP hải dương", []),
        ("Tp nam định", "Tp nam định", ["Tp nam định, luật 100k"]),
        ("tràng duệ", "tràng duệ", ["tràng duệ lạnh"]),
        ("từ liêm", "từ liêm", []),
        ("từ sơn", "từ sơn", []),
        ("văn giang", "văn giang", []),
        ("vân trung", "vân trung", []),
        ("vạn xuân thái nguyên", "vạn xuân thái nguyên", []),
        ("vin hà tĩnh", "vin hà tĩnh", []),
        ("vin hp", "vin hp", []),
        ("vnks", "vnks", []),
        ("võ cường", "võ cường", []),
        ("vsip bắc ninh", "vsip bắc ninh", []),
        ("vsip Bn", "vsip Bn", ["vsip Bn bốc 920k", "vsip Bn lạnh", "vsip bn lạnh, bốc"]),
        ("vsip Hp", "vsip Hp", ["vsip hp vé ct"]),
        ("vsip nghệ an", "vsip nghệ an", []),
        ("v tri", "v tri", []),
        ("vtrung", "vtrung", ["v trung", "vtrung đêm"]),
        ("yên bình thái nguyên", "yên bình thái nguyên", []),
        ("yên lập", "yên lập", []),
        ("yên mỹ", "yên mỹ", []),
        ("yên phong", "yên phong", []),
        ("yên sơn tuyên quang", "yên sơn tuyên quang", []),
        ("yên thế BG", "yên thế BG", []),
        ("YP", "YP", []),
    ];

    public static readonly (string[] StopCodes, string[] Aliases)[] Routes =
    [
        (["an tảo TP hưng yên", "nb"], ["an tảo TP hưng yên - nb"]),
        (["BT", "KQ"], ["BT - KQ"]),
        (["BT", "nb"], ["Bt - Nb", "bt- nb"]),
        (["BX 2", "nb"], ["BX 2- nb", "BX 2=- nb"]),
        (["BX", "nb"], ["BX - nb"]),
        (["bá thiện", "nb"], ["bá thiện - nb"]),
        (["bình xuyên", "nb"], ["bình xuyên - nb"]),
        (["chuyển kho als", "asg", "alsw"], ["chuyển kho als - asg - alsw"]),
        (["châu sơn", "nb"], ["châu sơn - nb"]),
        (["cảng Hp", "nb"], ["cảng Hp - nb chờ 3 giơf", "cảng hp - nb"]),
        (["cảng Hp", "nb QĐ"], ["cảng Hp - nb QĐ"]),
        (["cảng Hp", "vân trung"], ["cảng hp - vân trung"]),
        (["cầu giấy", "hà đong giấy"], ["cầu giấy - hà đông giấy"]),
        (["cẩm giàng HD", "nb"], ["cẩm giàng HD - nb"]),
        (["cẩm giàng", "nb"], ["cẩm giàng - nb"]),
        (["cẩm khê", "nb"], ["cẩm khê - nb"]),
        (["dthuy", "nb"], ["dthuy - nb kiẻm"]),
        (["dthuy", "vsip Bn"], ["dthuy - vsip Bn"]),
        (["dthy", "nb"], ["dthy - nb"]),
        (["dv 4", "nb"], ["dv 4 - nb kiểm"]),
        (["gia bình", "nb"], ["gia bình - nb"]),
        (["hiệp hoà", "nb"], ["hiệp hoà - nb\\"]),
        (["Hn giấy", "hợp thịnh BG"], ["hn giấy - hợp thịnh BG"]),
        (["Hn giấy", "nb"], ["HN giấy - nb"]),
        (["hà nội giấy", "thường tín", "nb"], ["hà nội giấy - thường tín - nb"]),
        (["hà trung", "nb"], ["hà trung - nb vé"]),
        (["hà đong", "nb"], ["hà đong - nb"]),
        (["hạ long", "nb"], ["hạ long - nb"]),
        (["hải hà", "nb"], ["hải hà - nb"]),
        (["KCn nội bài", "cảng Hp"], ["KCn nội bài - cảng hp"]),
        (["kim thành HD", "nb"], ["kim thành HD - nb"]),
        (["KQ", "dthuy", "KQ"], ["KQ - dthuy - KQ"]),
        (["KQ", "nb"], ["KQ - nb", "KQ - nb 2 kho"]),
        (["KQ", "phú hà"], ["KQ - phú hà"]),
        (["KQ", "T long"], ["KQ - t long"]),
        (["LGD", "nb"], ["LGD - nb cao tốc", "LGD - nb lưu đêm"]),
        (["LGE", "nb nguyên"], [":LGE - nb nguyên", "LGE - nb nguyên"]),
        (["LGE", "nb QĐ"], ["LGE - nb QĐ", "LGE - nb QĐ lưu ca đêm NBA", "LGE - nb QĐ lưu đêm"]),
        (["Lgi", "nb"], ["Lgi - nb", "lgi - nb lưu đêm", "lgi - nb lưu đêm 2 kho"]),
        (["Lgi", "nomura", "nb"], ["Lgi - nomura - nb kiểm"]),
        (["lâm thao", "cảng Hp"], ["lâm thao - cảng Hp"]),
        (["lương sơn", "nb"], ["lương sơn - nb"]),
        (["lạng giang", "nb"], ["lạng giang - nb"]),
        (["lập thạch", "nb"], ["lập thạch - nb"]),
        (["mỹ hào hy", "nb"], ["mỹ hào hy - nb"]),
        (["mỹ hào", "nb"], ["mỹ hào - nb"]),
        (["mỹ hào", "đồng văn"], ["mỹ hào - đòng văn"]),
        (["Mỹ thuận nam định", "nb"], ["Mỹ thuận nam định - nb kiểm"]),
        (["nbg", "hoà xá"], ["nbg - hoà xá"]),
        (["nb", "BT"], ["NB - BT lạnh", "Nb - BT"]),
        (["nb", "BX"], ["NB - BX"]),
        (["nb", "bình xuyên"], ["nb - bình xuyên"]),
        (["nb", "cảng Hp"], ["Nb - cảng Hp lạnh", "nb - cảng HP"]),
        (["nb", "cẩm giàng HD"], ["NB - cẩm giàng HD"]),
        (["nb", "dthuy"], ["Nb -D thuy"]),
        (["nb", "dv 4"], ["Nb - đv 4"]),
        (["nb", "hiệp hoà"], ["NB - hiệp hoà"]),
        (["nb", "Hn giấy"], ["NB - Hn giấy"]),
        (["nb", "honda phúc yên"], ["Nb - honda phúc yên"]),
        (["nb", "hoà phú", "đình trám", "hoà phú"], ["Nb - hoà phú - kiểm đình trám - hòa phú"]),
        (["nb", "HQVP", "BT"], ["NB - HQVP - BT kiểm"]),
        (["nb", "HY"], ["Nb - HY"]),
        (["nb", "hà nội giấy"], ["nb - hà nội giấy"]),
        (["nb", "hưng hà"], ["Nb - hưng hà"]),
        (["nb", "hạ long"], ["nb - hạ long"]),
        (["nb", "hạp lĩnh"], ["Nb - hạp lĩnh"]),
        (["nb", "hải dương"], ["nb - hải dương"]),
        (["nb", "hồng bàng HP"], ["Nb - hồng bàng HP"]),
        (["nb", "khai quang"], ["nb - khai quang bốc"]),
        (["nb", "kim thành HD"], ["NB - kim thành HD"]),
        (["nb", "KNQ BT"], ["Nb - KNQ BT", "Nb - KNQ BT chờ 200k"]),
        (["nb", "KNQ hà nam"], ["Nb - KNQ hà nam"]),
        (["nb", "KQ"], ["Nb - KQ"]),
        (["nb", "KQ", "BT", "nb"], ["Nb - kQ - BT - nb"]),
        (["nb", "LGD"], ["Nb - LGD", "Nb - LGD lạnh vé", "Nb - LGD rung vé", "Nb - LGD vé"]),
        (["nb", "LGE"], ["Nb - LGE"]),
        (["nb", "Lgi"], ["Nb - Lgi vé"]),
        (["nb", "lục nam"], ["Nb - lục nam"]),
        (["nb", "mong dương Qn"], ["NB - mong dương Qn"]),
        (["nb", "nam sách"], ["nb - nam sách"]),
        (["nb", "nghĩa trụ HY"], ["NB - nghĩa trụ HY"]),
        (["nb", "nomura"], ["nb - nomura"]),
        (["nb", "P NỐi A"], ["Nb - P Nối A"]),
        (["nb", "P NỐi B"], ["Nb - P Nối B"]),
        (["nb", "phù ninh"], ["Nb - phù ninh"]),
        (["nb", "phú hà"], ["Nb - phú hà"]),
        (["nb", "phú hà", "nb"], ["2 kho nb - phú hà - nb"]),
        (["nb", "phú nghĩa"], ["Nb - phú nghĩa"]),
        (["nb", "phổ yên"], ["NB - phổ yên"]),
        (["nb", "phủ lý"], ["NB - phủ lý lưu nhà máy", "Nb - phủ lý", "nb -phủ lý"]),
        (["nb", "Qchau"], ["Nb - Qchau", "Nb - Qchau lạnh"]),
        (["nb", "QM"], ["Nb - QM"]),
        (["nb", "quang minh"], ["nb - quang minh"]),
        (["nb", "quế võ"], ["NB - quế võ"]),
        (["nb", "QV"], ["Nb - QV"]),
        (["nb", "QV 2"], ["Nb - QV 2"]),
        (["nb", "QV", "thuận thành"], ["NB - QV- thuận thành"]),
        (["nb", "song khê"], ["nb - song khê", "nb -song khê"]),
        (["nb", "sông cong"], ["NB - song cong"]),
        (["nb", "T long"], ["nb - T long"]),
        (["nb", "thuận thành"], ["Nb - thuận thành"]),
        (["nb", "thăng long 2"], ["nb - thăng long 2 lạnh"]),
        (["nb", "tiên du"], ["NB - tiên du"]),
        (["nb", "tiên sơn"], ["N b - tiên sơn"]),
        (["nb", "tiên xuân thạch thất"], ["NB - tiên xuân thạch thất"]),
        (["nb", "Tp bắc giang"], ["Nb - Tp bắc giang"]),
        (["nb", "TP bắc ninh", "vsip Bn"], ["Nb 2 kho - TP bắc ninh - vsip Bn"]),
        (["nb", "Tp nam định"], ["Nb - Tp nam định, luật 100k"]),
        (["nb", "tràng duệ"], ["Nb - tràng duệ"]),
        (["nb", "từ liêm"], ["NB - từ liêm"]),
        (["nb", "vin hà tĩnh"], ["Nb - vin hà tĩnh"]),
        (["nb", "vsip Bn"], ["Nb - vsip Bn", "nb - vsip Bn lạnh", "nb - vsip bn lạnh, bốc"]),
        (["nb", "vsip bắc ninh"], ["nb - vsip bắc ninh"]),
        (["nb", "vsip Hp"], ["Nb - vsip hp vé ct"]),
        (["nb", "vsip nghệ an"], ["Nb - vsip nghệ an"]),
        (["nb", "vtrung"], ["Nb - Vtrung", "Nb -v trung", "nb - vtrung đêm"]),
        (["nb", "võ cường"], ["Nb - võ cường", "Nb- võ cường"]),
        (["nb", "văn giang"], ["Nb - văn giang"]),
        (["nb", "YP"], ["Nb - YP"]),
        (["nb", "yên mỹ"], ["Nb - yên mỹ"]),
        (["nb", "đong mai QN"], ["NB - đong mai QN", "Nb 2 kho - đong mai Qn, 100k chờ lấy hàng"]),
        (["nb", "đv"], ["4 kho NB - đv", "NB - đv lạnh", "Nb - ĐV"]),
        (["nb", "đông trièu QN"], ["nb - đông trièu QN"]),
        (["nb", "Đại An"], ["Nb - Đại An"]),
        (["nb", "đại đồng"], ["Nb - đại đòng", "nb - đại đồng"]),
        (["nb", "đồng văn"], ["NB - đồng văn"]),
        (["nghi lộc", "nb"], ["nghi lộc - nb"]),
        (["NGuyên khê", "T long"], ["NGuyên khê - T long"]),
        (["NGọc hồi", "bắc ninh"], ["NGọc hồi - bắc ninh"]),
        (["NGọc hồi", "nb"], ["ngọc hồi - nb", "ngọc hồi =- NB"]),
        (["nhà máy chè", "hà nội giấy"], ["nhà máy chè - hà nội giấy 2 điểm"]),
        (["nhà máy chè", "hà đong giấy"], ["nhà máy chè - hà đong giấy", "nhà máy chè - hà đông giáy"]),
        (["nhà máy chè", "hà đong giấy + Hn giấy"], ["nhà máy chè - hà đong giấy + Hn giấy"]),
        (["nhà máy chè", "sơn đồng Hn", "hoài đức"], ["nhà máy chè - sơn đồng Hn - hoài đức"]),
        (["nhà máy chè", "thanh trì"], ["nhà máy chè - thanh trì"]),
        (["Nn", "phú bài huế"], ["Nn - phú bài huế"]),
        (["nomura", "hạp lĩnh"], ["nomura - hạp lĩnh ;lạnh"]),
        (["P NỐi A", "nb"], ["P NỐi A - NB"]),
        (["P NỐi A", "đv"], ["P NỐi A - đv"]),
        (["P NỐi B", "T long"], ["P NỐi B - T long"]),
        (["phù ninh", "nb"], ["phù ninh - nb, vé"]),
        (["phú hà", "cảng Hp"], ["phú hà - cảng hp"]),
        (["phú hà", "nb"], ["Phú hà - nb vé", "phú hà - nb"]),
        (["Phú thọ", "HY"], ["Phú thọ - HY"]),
        (["phúc thọ", "Hn", "nb"], ["phúc thọ - Hn - nb ko hàng"]),
        (["phúc yên", "vin hp"], ["phúc yên - vin hp"]),
        (["Phúc điền", "QM"], ["phúc điền - Qm"]),
        (["Phúc điền", "tiên sơn"], ["Phúc điền - tiên sơn"]),
        (["phổ yên", "cảng Hp"], ["phổ yên - cảng Hp"]),
        (["Qchau", "nb"], ["Qchau - nb", "Qchau - nb lưu đêm + 2 kho", "Qchau =- nb"]),
        (["QM", "BT"], ["Qm - BT"]),
        (["QM", "nam sách", "QM"], ["QM - nam sách - QM"]),
        (["QM", "nb"], ["QM - nb", "Qm - nb lạnh"]),
        (["QM", "QM", "QM"], ["Qm - QM - Qm"]),
        (["QM", "T long"], ["QM - T long lạnh"]),
        (["QM", "T long", "nb"], ["QM- T long - NB lạnh"]),
        (["QM", "tân quang"], ["QM - tân quang"]),
        (["QM", "tân trường", "Đại An"], ["QM - tân trường - đại an"]),
        (["quang minh", "thái bình"], ["quang minh - thái bình"]),
        (["quang minh", "đông mai"], ["quang minh - đông mai"]),
        (["QV 2", "Qchau", "nb"], ["QV 2- Qchau - nb"]),
        (["QV 3", "từ sơn", "nb"], ["QV 3 - từ sơn - nb"]),
        (["QV", "BX"], ["QV - bX"]),
        (["QV", "hQQV", "QV"], ["QV - hQQV - QV kiểm"]),
        (["QV", "nb"], ["QV - nb", "QV =- nb", "qv- nb 3 kho + chờ 200k"]),
        (["QV", "NGọc hồi"], ["QV - ngọc hôi"]),
        (["QV", "vsip Bn", "nb"], ["QV - vsip Bn - nb"]),
        (["shinwon", "cảng Hp"], ["shinwon - cảng Hp"]),
        (["song khê", "nb"], ["song khê - nb"]),
        (["sóc sơn", "vin hp"], ["sóc sơn - vin hp"]),
        (["sông cong", "nb"], ["sông cong - nb", "sông công - nb"]),
        (["sông cong", "Đại An"], ["sông cong - Đại An"]),
        (["T long 2", "nb"], ["T long 2 - nb"]),
        (["T longb", "mỹ hào"], ["T longb - mỹ hào"]),
        (["T long", "dthuy"], ["T long -d thuy"]),
        (["T long", "nb"], ["T long - NB 2 kho", "T long - nb lạnh"]),
        (["T long", "QM"], ["T long - QM", "T long - QM lạnh"]),
        (["T long", "QV"], ["T long - QV lạnh"]),
        (["T long", "QV", "T long"], ["T long - QV - T long"]),
        (["T long", "sông khoai QN"], ["t long - sông khoai QN"]),
        (["T long", "T long"], ["T long - t long lạnh"]),
        (["T long", "tràng duệ"], ["T long - tràng duệ lạnh"]),
        (["tam dương", "BT", "tam dương"], ["tam dương - bt - tam dương"]),
        (["thanh hoá", "đà nẵng"], ["thanh hoá - đà nẵng"]),
        (["thanh thuỷ", "cảng Hp"], ["thanh thuỷ - cảng Hp"]),
        (["thanh trì", "nb"], ["thanh trì - nb"]),
        (["thanh trì", "vtrung"], ["thanh trì - vtrung"]),
        (["thuận thành", "hoài đức"], ["thuận thành - hoài đức"]),
        (["thuận thành", "thăng long"], ["thuận thành - thăng long"]),
        (["thuỵ vân", "nb"], ["thuỵ vân - nb"]),
        (["thuỵ vân", "sevt"], ["thuỵ vân - sevt bốc 100k"]),
        (["thạch thất", "tiên sơn"], ["thạch thất - tiên sơn"]),
        (["thạch thất", "đình trám"], ["thạch thất - đình trám"]),
        (["tiên sơn", "HQ tiên sơn", "nb"], ["tiên sơn - HQ tiên sơn - nb kiểm"]),
        (["tiên sơn", "nb"], ["tiên sơn - nb"]),
        (["tiên sơn", "QV"], ["tiên sợn - QV"]),
        (["TP bắc ninh", "nb"], ["tp bắc ninh - nb"]),
        (["TP hải dương", "vsip nghệ an"], ["TP hải dương - vsip nghệ an"]),
        (["tràng duệ", "nb"], ["tràng duệ - nb"]),
        (["tân chi", "vsip Bn"], ["tân chi - vsip Bn bốc 920k"]),
        (["tân yên", "hà nội giấy"], ["tân yên - hà nội giấy"]),
        (["từ sơn", "QM"], ["từ sơn - QM"]),
        (["vin hp", "nb"], ["vin hp - nb"]),
        (["vnks", "nb"], ["vnks - nb"]),
        (["vsip Bn", "BT"], ["vsip Bn - BT", "vsip Bn - bt lạnh"]),
        (["vsip Bn", "nb"], ["vsip Bn - nb", "vsip Bn - nb chờ 150k", "vsip Bn =- nb", "vsip bn - nb đeem"]),
        (["vsip Hp", "nb"], ["vsip HP - nb"]),
        (["vsip nghệ an", "nb"], ["vsip nghệ an - nb, vé"]),
        (["võ cường", "Qchau"], ["võ cường - Qchau, chèn 80k"]),
        (["vạn xuân thái nguyên", "nb"], ["vạn xuân thái nguyên - nb"]),
        (["YP", "nb"], ["YP - nb"]),
        (["YP", "sơn la"], ["YP - sơn la, 560k lưu đêm"]),
        (["YP", "vtrung"], ["YP - vtrung"]),
        (["yên bình thái nguyên", "nb"], ["yên bình thái nguyên - nb"]),
        (["yên lập", "nb"], ["yên lập - nb"]),
        (["yên lập", "v tri"], ["yên lập -v tri"]),
        (["yên phong", "hoa quân nghệ an"], ["yên phong - hoa quân nghệ an"]),
        (["yên sơn tuyên quang", "nb"], ["yên sơn tuyên quang - nb, 200k chờ"]),
        (["yên thế BG", "nb"], ["yên thế BG - nb"]),
        (["ân thi", "nb"], ["ân thi - nb"]),
        (["đong hưng thái bình", "nb"], ["đong hưng thái bình - nb", "đong hưng thái bình - nb chờ 300k"]),
        (["đv", "BX"], ["Đv - bx cao tốc"]),
        (["đv", "hạp lĩnh"], ["đv - hạp lĩnh"]),
        (["đv", "nb"], ["đv - nb", "đv - nb cao tốc", "đv - nb lưu xe", "đv - nb lưu đêm", "đv - nb vé", "đv =- nb", "đv =- nb vé ct"]),
        (["đình trám", "nb"], ["đình trám - nb"]),
        (["đông mai", "nb"], ["đông mai - nb"]),
        (["đường hào HY", "nb"], ["đường hào HY - nb"]),
        (["Đại An", "nb"], ["Đại An - nb"]),
        (["đại đồng", "nb"], ["đại đồng - nb"]),
        (["định hoá thái nguyên", "nam định 2 chiều"], ["định hoá thái nguyên - nam định 2 chiều"]),
        (["đồng văn", "nb"], ["đồng văn - nb", "đồng văn - nb , vé", "đồng văn -nb"]),
    ];

    public static readonly (string Code, string Name, string Description, string[] Aliases)[] Locations_1 =
    [
        ("DHA", "Công ty TNHH một thành viên DHA Bắc Ninh", "Cụm công Nghiệp Táo Đôi, thị trấn Thứa, Lương Tài, Bắc Ninh", []),
        ("NMQ", "Công ty cổ phần tiếp vận NMQ", "Số 12, ngõ 93, phố trung kính, phường Trung Hòa, quận Cầu giấy, TP Hà Nội", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
        ("", "", "", []),
    ];
}
